languages:
  Ruby: true
exclude_paths:
- "spec/controllers/api/api_keys_controller_spec.rb"
- "spec/controllers/api/base_controller_spec.rb"
- "spec/controllers/api/sessions_controller_spec.rb"
- "spec/controllers/api/signups_controller_spec.rb"
- "spec/routing/api/sessions_routing_spec.rb"
- "spec/routing/api/signups_routing_spec.rb"
- "spec/routing/api/api_keys_routing_spec.rb"
- "spec/policies/api_key_policy_spec.rb"
- "spec/decorators/api_key_decorator_spec.rb"
- "spec/decorators/secure_token_decorator_spec.rb"
- "spec/decorators/user_decorator_spec.rb"
- "spec/lib/api/session_spec.rb"
- "spec/lib/api/signup_spec.rb"
