---
EnableDefaultLinters: true
glob: "app/**/*.{html,text,js}{+*,}.erb"
linters:
  ErbSafety:
    enabled: false
  SelfClosingTag:
    enabled: true
    enforced_style: "never"
  Rubocop:
    enabled: true
    rubocop_config:
      require: standard
      inherit_gem:
        standard: config/base.yml
      inherit_from: .erb_lint_rubocop.yml
      AllCops:
        DisabledByDefault: true
