AllCops:
  Exclude:
    - 'bin/*'
    - 'config/spring.rb'
    - 'db/schema.rb'
    - 'db/migrate/20170107151911_add_rpush.rb'
    - 'db/migrate/20170107151912_rpush_2_0_0_updates.rb'
    - 'db/migrate/20170107151913_rpush_2_1_0_updates.rb'
    - 'db/migrate/20170107151914_rpush_2_6_0_updates.rb'
    - 'db/migrate/20170107151915_rpush_2_7_0_updates.rb'
    - 'db/migrate/20171129190142_create_active_storage_tables.active_storage.rb'
    - 'db/migrate/20171129191705_rpush_3_0_0_updates.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'OLD/**/*'

Naming/FileName:
  Exclude:
    - 'config/initializers/sentry-raven.rb'
    - 'config/initializers/rack-cors.rb'
    - 'spec/support/shoulda-matchers.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/api/docs_controller.rb'
    - 'app/documentation/api/docs/**/*.rb'
    - 'app/views/api/**/*.json.jbuilder'
    - 'config/routes.rb'
    - 'config/sitemap.rb'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/documentation/api/docs/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'
