AllCops:
  Exclude:
    - "bin/*"
    - "config/spring.rb"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/WordArray:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false
