require:
  - rubocop-disable_syntax
  - rubocop-performance
  - rubocop-graphql
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/data_schema.rb"
    - "vendor/**/*"

Style/DisableSyntax:
  DisableSyntax:
    - unless
    - ternary
    - endless_methods
    - numbered_parameters
    - shorthand_hash_syntax
    - percent_literals

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

GraphQL/OrderedFields:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: snake_case
  Exclude:
    - "config/initializers/ancestry.rb"

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/RescueStandardError:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

GraphQL/ObjectDescription:
  Exclude:
    - "app/graphql/evemonk_schema.rb"
    - "app/graphql/types/node_type.rb"
    - "app/graphql/mutations/base_mutation.rb"
    - "app/graphql/types/base_argument.rb"
    - "app/graphql/types/base_connection.rb"
    - "app/graphql/types/base_edge.rb"
    - "app/graphql/types/base_enum.rb"
    - "app/graphql/types/base_field.rb"
    - "app/graphql/types/base_input_object.rb"
    - "app/graphql/types/base_interface.rb"
    - "app/graphql/types/base_object.rb"
    - "app/graphql/types/base_scalar.rb"
    - "app/graphql/types/base_union.rb"
    - "app/graphql/sources/eve_category_by_category_id.rb"

GraphQL/ExtractType:
  Prefixes:
    - is
    - with
    - avg
    - min
    - max
    - sof
    - executor
    - creator
    - ship
    - home
    - militia
    - solar
    - station
    - parent
    - market

Style/HashSyntax:
  Enabled: false

# Disabled as in standard
Lint/EmptyFile:
  Enabled: false

# Disabled as in standard
Style/NegatedIf:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/HookArgument:
  Enabled: true
  Exclude:
    - "spec/support/database_rewinder.rb"
    - "spec/support/prosopite.rb"

RSpec/StubbedMock:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - "spec/integration/graphql/*_spec.rb"
    - "spec/system/**/*_spec.rb"

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: true
  EnforcedStyle: disallow

RSpec/LetBeforeExamples:
  Enabled: false

RSpec/HooksBeforeExamples:
  Enabled: false

# Enable and fix later...
Capybara/ClickLinkOrButtonStyle:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

GraphQL/FieldDefinitions:
  Enabled: false
