AllCops:
  Exclude:
    - 'bin/*'
    - 'config/spring.rb'
    - 'db/schema.rb'
    - 'db/migrate/20170107151911_add_rpush.rb'
    - 'db/migrate/20170107151912_rpush_2_0_0_updates.rb'
    - 'db/migrate/20170107151913_rpush_2_1_0_updates.rb'
    - 'db/migrate/20170107151914_rpush_2_6_0_updates.rb'
    - 'db/migrate/20170107151915_rpush_2_7_0_updates.rb'
    - 'db/migrate/20171129190142_create_active_storage_tables.active_storage.rb'
    - 'node_modules/**/*'
