require: rubocop-thread_safety
require: rubocop-rspec
require: rubocop-performance

inherit_from:
  - .rubocop_general.yml
  - .rubocop_rspec.yml
  - .rubocop-thread_safety.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/spring.rb'
    - 'db/schema.rb'
    - 'db/migrate/20170107151911_add_rpush.rb'
    - 'db/migrate/20170107151912_rpush_2_0_0_updates.rb'
    - 'db/migrate/20170107151913_rpush_2_1_0_updates.rb'
    - 'db/migrate/20170107151914_rpush_2_6_0_updates.rb'
    - 'db/migrate/20170107151915_rpush_2_7_0_updates.rb'
    - 'db/migrate/20171129191705_rpush_3_0_0_updates.rb'
    - 'db/migrate/20171129190142_create_active_storage_tables.active_storage.rb'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/api/docs_controller.rb'
    - 'app/documentation/**/*.rb'
    - 'config/routes.rb'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/documentation/**/*.rb'

# Bug in rubocop-rspec cop
RSpec/FilePath:
  Exclude:
    - 'spec/routing/**/*.rb'

# Possibly bug in rubocop-rspec cop
RSpec/ExampleLength:
  Exclude:
    - 'spec/routing/**/*.rb'

RSpec/MultipleDescribes:
  Exclude:
    - 'spec/policies/**/*.rb'

Naming/FileName:
  Exclude:
    - 'config/initializers/rack-cors.rb'
    - 'spec/support/shoulda-matchers.rb'

Style/MethodCallWithArgsParentheses:
  Exclude:
    - 'db/migrate/*.rb'
    - 'spec/**/*_spec.rb'
