require:
  - rubocop-performance
  - rubocop-graphql

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

GraphQL/OrderedFields:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: snake_case

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

GraphQL/ExtractType:
  Prefixes:
    - is
    - with
    - avg
    - min
    - max
    - sof
    - executor
    - creator
    - ship
    - home
    - militia
    - solar
    - station
    - parent
    - market
