ruby_version: 3.3
parallel: true

ignore:
  - "bin/*"
  - "db/schema.rb"
  - "db/data_schema.rb"
  - "db/cache_schema.rb"
  - "db/cable_schema.rb"
  - "db/queue_schema.rb"
  - "db/rails_pulse_schema.rb"
  - "vendor/**/*"
