volumes:
  evemonk_postgresql_data:
    external: true
  evemonk_redis_data:
    external: true
  evemonk_meilisearch_data:
    external: true

services:
  postgresql:
    image: "docker.io/library/postgres:18"
    container_name: "evemonk_postgresql"
    restart: "unless-stopped"
    volumes:
      - "evemonk_postgresql_data:/var/lib/postgresql/data:rw"
      - "./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  meilisearch:
    image: "docker.io/getmeili/meilisearch:v1.43.1"
    container_name: "evemonk_meilisearch"
    restart: "unless-stopped"
    volumes:
      - "evemonk_meilisearch_data:/meili_data:rw"
    environment:
      MEILI_MASTER_KEY: "secret"
    ports:
      - "7700:7700"

  redis:
    image: "docker.io/valkey/valkey:9.0"
    container_name: "evemonk_redis"
    restart: "unless-stopped"
    volumes:
      - "evemonk_redis_data:/data:rw"
    ports:
      - "6379:6379"
