volumes:
  evemonk_postgresql_data:
    external: true
  evemonk_redis_data:
    external: true
  evemonk_typesense_data:
    external: true

services:
  postgresql:
    image: "docker.io/library/postgres:18"
    container_name: "evemonk_postgresql"
    restart: "unless-stopped"
    volumes:
      - "evemonk_postgresql_data:/var/lib/postgresql/data:rw"
      - "./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  typesense:
    image: "docker.io/typesense/typesense:30.2"
    container_name: "evemonk_typesense"
    restart: "unless-stopped"
    volumes:
      - "evemonk_typesense_data:/data:rw"
    environment:
      TYPESENSE_API_KEY: "API_KEY"
      TYPESENSE_DATA_DIR: "/data"
      TYPESENSE_ENABLE_CORS: "true"
    ports:
      - "8108:8108"

  redis:
    image: "docker.io/valkey/valkey:9.1"
    container_name: "evemonk_redis"
    restart: "unless-stopped"
    volumes:
      - "evemonk_redis_data:/data:rw"
    ports:
      - "6379:6379"
