FROM ruby:2.6.5-slim

LABEL maintainer="Igor Zubkov <igor.zubkov@gmail.com>"

RUN apt-get update -y && \
    apt-get dist-upgrade -y && \
    apt-get install gnupg2 git gcc g++ make wget curl wait-for-it libpq-dev --no-install-recommends -y

RUN sh -c 'curl -sL https://deb.nodesource.com/setup_10.x | bash -'

RUN sh -c 'curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -'

RUN sh -c 'echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list'

RUN apt-get update -y && \
    apt-get install nodejs yarn --no-install-recommends -y

RUN apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app

WORKDIR /app

ENV GEM_HOME=/bundle
ENV BUNDLE_JOBS=4
ENV BUNDLE_RETRY=3
ENV BUNDLE_PATH $GEM_HOME
ENV BUNDLE_APP_CONFIG=$BUNDLE_PATH

ENV RUBYGEMS_VERSION 3.0.6

RUN gem update --system "$RUBYGEMS_VERSION"

ENV BUNDLER_VERSION 2.1.0.pre.2

RUN gem install bundler --version "$BUNDLER_VERSION" --force

COPY . .
