# copy to config/evemonk.yml and configure

test:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  slack:
    updates_webhook_channel_url: ""
  jobs:
    character:
      info: true
      assets: true
      standings: true
      wallet_job: true
    eve:
      server_status: true

development:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  slack:
    updates_webhook_channel_url: ""
  jobs:
    character:
      info: true
      assets: true
      standings: true
      wallet_job: true
    eve:
      server_status: true

production:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  slack:
    updates_webhook_channel_url: ""
  jobs:
    character:
      info: true
      assets: true
      standings: true
      wallet_job: true
    eve:
      server_status: true
