# copy to config/evemonk.yml and configure

test:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  use_image_proxy: false
  image_proxy_url: "https://imageproxy.evemonk.com/"
  use_google_search_console: false
  use_fathom_evemonk: false
  jobs:
    character: true
    eve:
      update_alliance: true
      update_corporation: true
  slack:
    updates_webhook_channel_url: ""

development:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  use_image_proxy: true
  image_proxy_url: "https://imageproxy.evemonk.com/"
  use_google_search_console: false
  use_fathom_evemonk: false
  jobs:
    character: true
    eve:
      update_alliance: true
      update_corporation: true
  slack:
    updates_webhook_channel_url: ""

production:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  use_image_proxy: true
  image_proxy_url: "https://imageproxy.evemonk.com/"
  use_google_search_console: true
  google_site_verification_token: ""
  use_fathom_evemonk: true
  jobs:
    character: true
    eve:
      update_alliance: true
      update_corporation: true
  slack:
    updates_webhook_channel_url: ""
