# copy to config/evemonk.yml and configure

test:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  slack:
    updates_webhook_channel_url: ""
  pghero: false
  jobs:
    character:
      info: false
      assets: false
      standings: false
      wallet_job: false
    eve:
      server_status: false
      bloodlines: false
      factions: false
      update_alliance: false
      update_alliances: false
      local_alliances: false
      update_alliance_logo: false
      update_alliance_corporations: false
      update_alliances_corporations: false
    update_characters: false
    import_missing: false

development:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  slack:
    updates_webhook_channel_url: ""
  pghero: true
  jobs:
    character:
      info: false
      assets: false
      standings: false
      wallet_job: false
    eve:
      server_status: true
      bloodlines: true
      factions: true
      update_alliance: false
      update_alliances: false
      local_alliances: false
      update_alliance_logo: false
      update_alliance_corporations: false
      update_alliances_corporations: false
    update_characters: false
    import_missing: false

production:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  slack:
    updates_webhook_channel_url: ""
  pghero: false
  jobs:
    character:
      info: false
      assets: false
      standings: false
      wallet_job: false
    eve:
      server_status: false
      bloodlines: false
      factions: false
      update_alliance: false
      update_alliances: false
      local_alliances: false
      update_alliance_logo: false
      update_alliance_corporations: false
      update_alliances_corporations: false
    update_characters: false
    import_missing: false
