# copy to config/evemonk.yml and configure

test:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  slack:
    updates_webhook_channel_url: ""

development:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  use_image_proxy: "true"
  image_proxy_url: "https://imageproxy.evemonk.com/"
  slack:
    updates_webhook_channel_url: ""

production:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  use_image_proxy: "true"
  image_proxy_url: "https://imageproxy.evemonk.com/"
  slack:
    updates_webhook_channel_url: ""
