# copy to config/evemonk.yml and configure

test:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  slack:
    updates_webhook_channel_url: ""
  jobs:
    character:
      info: true
      assets: true
      standings: true
      wallet_job: true
    eve:
      server_status: true
      update_alliance: true
      update_alliances: true
      local_alliances: true
      update_alliance_logo: true
      update_alliance_corporations: true
      update_alliances_corporations: true
    update_characters: true

development:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  slack:
    updates_webhook_channel_url: ""
  jobs:
    character:
      info: true
      assets: true
      standings: true
      wallet_job: true
    eve:
      server_status: true
      update_alliance: true
      update_alliances: true
      local_alliances: true
      update_alliance_logo: true
      update_alliance_corporations: true
      update_alliances_corporations: true
    update_characters: true

production:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  slack:
    updates_webhook_channel_url: ""
  jobs:
    character:
      info: true
      assets: true
      standings: true
      wallet_job: true
    eve:
      server_status: true
      update_alliance: true
      update_alliances: true
      local_alliances: true
      update_alliance_logo: true
      update_alliance_corporations: true
      update_alliances_corporations: true
    update_characters: true
