# copy to config/evemonk.yml and configure

test:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  features:
    image_proxy: false
    image_proxy_url: "https://imageproxy.evemonk.com/"
    google_search_console: false
    google_site_verification_token: ""
    fathom: false
  beta:
    assets: false
    mails: false
    neural_map_available: false
    standings: false
    wallet_journal: false
    wallet_transactions: false
    industry_jobs: false
    character_orders: false
    manufacturing_jobs: false
  slack:
    updates_webhook_channel_url: ""
  jobs:
    character:
      info: true
      assets: true
      standings: true
      wallet_job: true
    eve:
      server_status: true
      update_alliance: true
      update_alliances: true
      local_alliances: true
      update_alliance_logo: true
      update_alliance_corporations: true
      update_alliances_corporations: true
    update_characters: true
    import_missing: true

development:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  features:
    image_proxy: false
    image_proxy_url: "https://imageproxy.evemonk.com/"
    google_search_console: false
    google_site_verification_token: ""
    fathom: false
  beta:
    assets: false
    mails: false
    neural_map_available: false
    standings: false
    wallet_journal: false
    wallet_transactions: false
    industry_jobs: false
    character_orders: false
    manufacturing_jobs: false
  slack:
    updates_webhook_channel_url: ""
  jobs:
    character:
      info: true
      assets: true
      standings: true
      wallet_job: true
    eve:
      server_status: true
      update_alliance: true
      update_alliances: true
      local_alliances: true
      update_alliance_logo: true
      update_alliance_corporations: true
      update_alliances_corporations: true
    update_characters: true
    import_missing: true

production:
  eve_online_sso:
    client_id: ""
    secret_key: ""
  features:
    image_proxy: true
    image_proxy_url: "https://imageproxy.evemonk.com/"
    google_search_console: true
    google_site_verification_token: ""
    fathom: true
  beta:
    assets: false
    mails: false
    neural_map_available: false
    standings: false
    wallet_journal: false
    wallet_transactions: false
    industry_jobs: false
    character_orders: false
    manufacturing_jobs: false
  slack:
    updates_webhook_channel_url: ""
  jobs:
    character:
      info: true
      assets: true
      standings: true
      wallet_job: true
    eve:
      server_status: true
      update_alliance: true
      update_alliances: true
      local_alliances: true
      update_alliance_logo: true
      update_alliance_corporations: true
      update_alliances_corporations: true
    update_characters: true
    import_missing: true
