require: rubocop-thread_safety
require: rubocop-rspec
require: rubocop-performance

inherit_from:
  - .rubocop_general.yml
  - .rubocop_rspec.yml
  - .rubocop-thread_safety.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/api/docs_controller.rb'
    - 'app/documentation/**/*.rb'
    - 'config/routes.rb'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/documentation/**/*.rb'

# Bug in rubocop-rspec cop
RSpec/FilePath:
  Exclude:
    - 'spec/routing/**/*.rb'

# Possibly bug in rubocop-rspec cop
RSpec/ExampleLength:
  Exclude:
    - 'spec/routing/**/*.rb'

RSpec/MultipleDescribes:
  Exclude:
    - 'spec/policies/**/*.rb'

Naming/FileName:
  Exclude:
    - 'config/initializers/rack-cors.rb'
    - 'spec/support/shoulda-matchers.rb'

Style/MethodCallWithArgsParentheses:
  Exclude:
    - 'db/migrate/*.rb'
    - 'spec/**/*_spec.rb'
