name: Bundler Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 21 * * 6"

jobs:
  bundle-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Bundler Audit"
        uses: andrewmcodes/bundler-audit-action@main
