name: consistency_fail

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  POSTGRES_HOST_AUTH_METHOD: "trust"
  POSTGRES_USER: "runner"
  POSTGRES_DB: "evemonk_test"
  PGHOST: "localhost"
  SECRET_KEY_BASE: "df85f70fa713b189c61deba6a51206472643e53894ae9a1dcd7c97ee15a9b79e962c9ada5b12e69ab360648f74b89d1b7d26dd310b485d48d4509a3445113813"
  AWS_ACCESS_KEY_ID: "root"
  AWS_SECRET_ACCESS_KEY: "password"
  MINIO_REGION_NAME: "us-east-1"
  MINIO_ENDPOINT: "http://localhost:9000"
  BUCKET: "evemonk-test-bucket"

jobs:
  consistency_fail:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: "postgres:13.4"
        env:
          POSTGRES_HOST_AUTH_METHOD: "trust"
          POSTGRES_USER: "runner"
          POSTGRES_DB: "evemonk_test"
        ports:
          - "5432:5432"
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      minio:
        image: "minio/minio"
        env:
          MINIO_ROOT_USER: "root"
          MINIO_ROOT_PASSWORD: "password"
          MINIO_REGION_NAME: "us-east-1"
        ports:
          - "9000:9000"
          - "9001:9001"
        options: minio/minio server /data

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: rails db:create
        run: bundle exec rails db:create
      - name: rails db:migrate
        run: bundle exec rails db:migrate
      - name: run consistency_fail
        run: bundle exec consistency_fail
