name: Rails assets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: "0 21 * * 6"

permissions:
  contents: read

env:
  DEVISE_MAILER_SENDER: "robot@evemonk.com"
  ACTION_MAILER_FROM: "EveMonk <robot@evemonk.com>"
  DEVISE_PEPPER: "e19db51a470b8259e79616ac00450ea1857d819aa860e2e7cff79b3c295d3993867a68c9524587d2b02b6f76efa8dea8aaf09884f186bfab89442eb2530ea829"

jobs:
  precompile:
    runs-on: ubuntu-24.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up Ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          rubygems: latest
          bundler: latest
          bundler-cache: true
      - name: Disable skylight dev warning
        run: bundle exec skylight disable_dev_warning
      - run: cp -f config/evemonk.example.yml config/evemonk.yml
      - run: bin/rails SECRET_KEY_BASE=no assets:precompile
