name: yarn audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 21 * * 6"

jobs:
  yarn-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: Yarn versions
        run: yarn versions
      - name: yarn audit
        run: yarn audit
